[package]
name = "serde_arrow"
version = "0.1.0"
authors = ["Christopher Prohm <mail@cprohm.de>"]
edition = "2018"
description  = "convert sequences of structs / maps to arrow tables"
readme = "../Readme.md"
repository = "https://github.com/chmp/serde_arrow"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "5.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4" }
